apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QVNJQVc3RVA3Q0NUNjc0MlJSTjI=
  aws_secret_access_key: T2tCRmhpVW1GWDJKNWdWWTgxNkR6UXk3RUV1c0xwTTUwd1JZQ3poVw==