apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: backend-feed
    role: feed
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-feed
    role: feed
    tier: backend