apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-feed-hpa  
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: backend-feed-
    subresource: scale
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50